### ISSUE TITLE
Does it support Department with List<Employee>?

### ISSUE THREAD

**Issue by ThisNoName** [ababik/Remute#2]
Or do we still need System.Collections.Immutable for that?  Thanks

**Comment by ababik** [comment]
@ThisNoName, could you give me some more details of what you want to achieve? Code example would be great.

**Comment by ThisNoName** [comment]
In your Organization/Department/Employee sample, the unchanged part of the objects reference to the original, making it very efficient.  I wonder what happened to List.  For example,

    public class Department
    {
        public List<Employee> Staff {get;set;}
        public Department(List<Employee> staff)   {
            Staff=staff
    }}

What happened when you do something like this
    var actual2 = remute.With(expected, x => x.Staff.First().FirstName, "Joe");

Does it change the original first item, or remute the firstname of first item, or the entire list. ?

In .NET, there's a System.Collections.Immutable handles generic can handle immutable list.  I wonder if I need to use

    public class Department{
        public ImmutableList<Employee> Staff{get;set;}
    }}

Thanks.

**Comment by ababik** [comment]
@ThisNoName, thanks for your inquiry.

Remute maps properties from provided expression to constructor parameters.
E.g. `remute.With(organization, x => x.DevelopmentDepartment.Manager.FirstName, "Joe");`
1) It creates new `Employee` object to set it as `Manager` property. `Employee` object is created by executing its constructor `Employee(Guid id, string firstName, string lastName)`. Where `id` and `lastName` parameter values are taken from `Manager` instance but `firstName` is "Joe".
2) It creates new `Department` object to set it as `DevelopmentDepartment` property. `Department` object is created by executing its constructor `Department(string title, Employee manager, ImmutableList<Employee> employees)`. Where `title` and `employees` parameter values are taken from `DevelopmentDepartment` instance but manager is the object created in step 1).
3) Same for `organization` object.

As you can see currently it operates with properties only. So your example `x.Staff.First().FirstName` won't work as you expected because it won't be able to find property `First` and corresponding constructor parameter. However I think it will be useful to support LINQ IEnumerable extension methods. In this case `Staff` is gonna be a new object with updated first element only. Other elements are the same references. I can definitely implement it. Please contact me if you think you can provide additional info to this feature.

Nevertheless, I'm not sure that it should support `List`. `List` is mutable type. But Remute is to simplify life dealing with immutable types.
What's the purpose in you example to have setter for Staff property? List and setter make you object structure mutable. Can you explain why?

My example is `ImmutableList<Employee> Employees { get; }`
So you can't just assign new collection as well as modify it. That's the whole purpose of immutability.

Hope this helped.
