### ISSUE TITLE
Feature - Allow specifying the constructor to use for activition

### ISSUE THREAD

**Issue by michael-wolfenden** [ababik/Remute#3]
`Remute` assumes that the type has a single constructor. however we often have types with multiple constructors (usually one was `private` and only used for serialization).

It would be nice to have a way to specify the specific constructor to use if there are multiple by providing a `Func<IEnumerable<ConstructorInfo>, ConstructorInfo>`  or via some other mechanism.

PS - Thanks for the library, it's been super useful to us

**Comment by ababik-frozenmountain** [comment]
@michael-wolfenden thank you for your feedback.
I already have some code that addresses described problem. It's just no pushed yet. I will do some testing and validation and inform you later this week how it can be used.

**Comment by ababik** [comment]
@michael-wolfenden thank you for your inquiry. Your feedback is appreciated. 

Now you can configure Remute to work with type with multiple constructors. You can do that providing `ActivationConfiguration` object to `Remute` constructor.

Here is an example.

```cs
    public class User
    {
        public int Id { get; }
        public string FirstName { get; }
        public string LastName { get; }

        public User(int id, string firstName, string lastName)
        {
            Id = id;
            FirstName = firstName;
            LastName = lastName;
        }

        public User(string firstNameNotMatchingPropertyName, string lastName)
        {
            FirstName = firstNameNotMatchingPropertyName;
            LastName = lastName;
        }
    }
```
```cs
var user = new User(1, "Joe", "Doe");
var constructor = user.GetType().GetConstructor(new[] { typeof(int), typeof(string), typeof(string) });

var config = new ActivationConfiguration().Configure(constructor);
var remute = new Remute(config);
```

Also using `ActivationConfiguration` you can solve the problem when constructor parameter and property names are not matching.
```cs
var user = new User(1, "Joe", "Doe");
var type = user.GetType();
var constructor = type.GetConstructor(new[] { typeof(string), typeof(string) });

var firstNameParameter = constructor.GetParameters().Single(x => x.Name == "firstNameNotMatchingPropertyName");
var firstNameProperty = type.GetProperty("FirstName");

var config = new ActivationConfiguration()
    .Configure(constructor, new Dictionary<ParameterInfo, PropertyInfo>() { [firstNameParameter] = firstNameProperty });

var remute = new Remute(config);
```

So `Configure` method is to specify which constructor to use and how to map object properties to constructor parameters.

Last but not least, you can avoid reflection using the overloaded method. I think that would be the most preferable method because it's refactoring friendlier.

```cs
var config = new ActivationConfiguration()
    .Configure<User>(x => new User(x.FirstName, x.LastName));

var remute = new Remute(config);
```
This expression is not actually executed. This is to point which constructor to use and how to map parameters.

Please let me know if you have any questions.

**Comment by kofifus** [comment]
Remute can also search for a matching constructors from all those available ?
